#pragma once

enum KEYS { UP, DOWN, LEFT, RIGHT, TAB, SHOOT, BOOST };
enum MENUS { MAIN_MENU, CONTROLS_MENU, CONNECT_MENU, DISCONNECTED_MENU };
const int SCREEN_WIDTH = 800;
const int SCREEN_HEIGHT = 600;